-- MySQL Script generated by MySQL Workbench
-- Wed May 25 13:29:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema desclients
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema desclients
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desclients` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `desclients` ;

-- -----------------------------------------------------
-- Table `desclients`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desclients`.`categorie` (
  `idcategorie` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `comedie` VARCHAR(45) NOT NULL,
  `aventure` VARCHAR(45) NOT NULL,
  `drame` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desclients`.`payementdesclients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desclients`.`payementdesclients` (
  `iddate de payement` VARCHAR(10) NOT NULL,
  `date de payement` DECIMAL(25,0) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`iddate de payement`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desclients`.`films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desclients`.`films` (
  `idfilms` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `titre` VARCHAR(45) NOT NULL,
  `date de sortie` DATETIME NOT NULL,
  `duree` VARCHAR(45) NOT NULL,
  `categorie_idcategorie` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `payementdesclients_iddate de payement` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idfilms`, `categorie_idcategorie`),
  INDEX `fk_films_categorie1_idx` (`categorie_idcategorie` ASC) VISIBLE,
  INDEX `fk_films_payementdesclients1_idx` (`payementdesclients_iddate de payement` ASC) VISIBLE,
  CONSTRAINT `fk_films_categorie1`
    FOREIGN KEY (`categorie_idcategorie`)
    REFERENCES `desclients`.`categorie` (`idcategorie`),
  CONSTRAINT `fk_films_payementdesclients1`
    FOREIGN KEY (`payementdesclients_iddate de payement`)
    REFERENCES `desclients`.`payementdesclients` (`iddate de payement`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desclients`.`identite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desclients`.`identite` (
  `ididentite` INT NOT NULL,
  `nom` VARCHAR(10) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `payementdesclients_iddate de payement` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ididentite`, `payementdesclients_iddate de payement`),
  INDEX `fk_identite_payementdesclients1_idx` (`payementdesclients_iddate de payement` ASC) VISIBLE,
  CONSTRAINT `fk_identite_payementdesclients1`
    FOREIGN KEY (`payementdesclients_iddate de payement`)
    REFERENCES `desclients`.`payementdesclients` (`iddate de payement`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desclients`.`identite_has_films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desclients`.`identite_has_films` (
  `identite_ididentite` INT NOT NULL,
  `films_idfilms` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `date de location` VARCHAR(45) NOT NULL,
  `date de retour` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`identite_ididentite`, `films_idfilms`),
  INDEX `fk_identite_has_films_films1_idx` (`films_idfilms` ASC) VISIBLE,
  INDEX `fk_identite_has_films_identite_idx` (`identite_ididentite` ASC) VISIBLE,
  CONSTRAINT `fk_identite_has_films_films1`
    FOREIGN KEY (`films_idfilms`)
    REFERENCES `desclients`.`films` (`idfilms`),
  CONSTRAINT `fk_identite_has_films_identite`
    FOREIGN KEY (`identite_ididentite`)
    REFERENCES `desclients`.`identite` (`ididentite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desclients`.`typedefilm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desclients`.`typedefilm` (
  `idtitre` VARCHAR(25) NOT NULL,
  `titre` VARCHAR(25) NOT NULL,
  `date de sortie` DATETIME NOT NULL,
  `duree` DATETIME NOT NULL,
  `films_idfilms` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `films_categorie_idcategorie` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  PRIMARY KEY (`idtitre`, `films_idfilms`, `films_categorie_idcategorie`),
  INDEX `fk_typedefilm_films1_idx` (`films_idfilms` ASC, `films_categorie_idcategorie` ASC) VISIBLE,
  CONSTRAINT `fk_typedefilm_films1`
    FOREIGN KEY (`films_idfilms` , `films_categorie_idcategorie`)
    REFERENCES `desclients`.`films` (`idfilms` , `categorie_idcategorie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
